### ISSUE TITLE
animation seems tedious to load

### ISSUE THREAD

**Issue by lewislepton** [Nazariglez/Gecko2D#87]
on looking a bit further at your animation process, it really seems a bit tedious to work with.

this is only from the samples ive seen, but having separate images per frame seems a bit 'uuurrrggghhh' & was just wondering if you have thought on how kha2d does it?

so you have 1 sprite sheet & split it up via the coderings

**Comment by lewislepton** [comment]
never mind I saw the lines I was looking for.

FORGET ALL THIS THAT YOU SEE HERE. EVEN THIS LINE ;)

**Comment by Nazariglez** [comment]
^^
